# Matrices and Vectors in Python

## Outine
- Introduction to Matrices and Vectors in Python
- Vectors and Lists
- Matrices
- Wrap up

  
## Introduction to Matrices and Vectors in Python
   
A matrix is a special case of two dimensional array where each data element is of the same size. So every matrix is also a two dimensional array but not vice versa. 



<img src="images/matrix.jpg" width="200">

We can think of a vector as a list of numbers. A vector is a tuple of one or more scalar values. Vectors are a foundational element of linear algebra. Vectors are used throughout the field of machine learning in the description of algorithms and processes such as the target variable (y) when training an algorithm.

<img src="images/vectors.png" width="200">


## Vectors and Lists

A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between square brackets **[ ]** .

We can turn lists into vectors by converting them to Numpy arrays. 

Let's look at an example:

In [14]:
import numpy as np

c_list = [1,2]
print("The list:",c_list)
print("Has length:", len(c_list))

c_vector = np.array(c_list)
print("The vector:", c_vector)
print("Has shape:",c_vector.shape)

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2,)


## Matrices

Python doesn't have a built-in type for matrices. However, we can treat a ``"list of a list"`` as a matrix.

See the Python code below:

In [15]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print(A)
print (type(A))

[[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
<class 'list'>


If we use the **NumPy** library (which is typically the workhorse for Linear Algebra), it has a multidimensional array object, called ``ndarray`` that we can use to represent a matrix.

See the example below:

In [16]:
import numpy as np
a = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])
print(a)               # Output: [1, 2, 3]
print(type(a))         # Output: <class 'numpy.ndarray'>

# numpy will tell us the shape of the matrix (array)
print('This is the shape of the array/matrix:', a.shape)         

[[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
<class 'numpy.ndarray'>
This is the shape of the array/matrix: (3, 4)


## Wrap up
We discussed:
- Introduction to Matrices and Vectors in Python
- Vectors and Lists
- Matrices
