# Eigenvalue and Eigenvectors

## Outine
- Introduction to Eigenvalue and Eigenvectors
- Calculation of Eigendecomposition
- Confirm an Eigenvector and Eigenvalue
- Reconstruct the original matrix
- Wrap up


  
## Introduction to Eigenvalue and Eigenvectors
   
Eigenvectors are unit vectors, which means that their length or magnitude is equal to 1.0. They are often referred as right vectors, which simply means a column vector (as opposed to a row vector or a left vector). 

Eigenvalues are coefficients applied to eigenvectors that give the vectors their length or magnitude. For example, a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it.

A matrix that has only positive eigenvalues is referred to as a positive definite matrix, whereas if the eigenvalues are all negative, it is referred to as a negative definite matrix.

For a square matrix A, an Eigenvector and Eigenvalue make this equation true (if we can find them, that is, it is solvable):

<img src="images/eigenvalue.svg" width="400">


## Calculation of Eigendecomposition

The example below first defines a 3×3 square matrix. The eigendecomposition is calculated on the matrix returning the eigenvalues and eigenvectors.


In [4]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Square matrix")
print(A)
# calculate eigendecomposition
values, vectors = eig(A)
print("Eigenvalues")
print(values)
print("Eigenvectors")
print(vectors)

Square matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Eigenvalues
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Confirm an Eigenvector and Eigenvalue
We do this by applying the formula above.

First, we will define a matrix, then calculate the eigenvalues and eigenvectors. We will then test whether the first vector and value are in fact an eigenvalue and eigenvector for the matrix. We know they are, but it is a good exercise.

The eigenvectors are returned as a matrix with the same dimensions as the parent matrix, where each column is an eigenvector, e.g. the first eigenvector is vectors[:, 0]. Eigenvalues are returned as a list, where value indices in the returned array are paired with eigenvectors by column index, e.g. the first eigenvalue at values[0] is paired with the first eigenvector at vectors[:, 0].

In [2]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# calculate eigendecomposition
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print("confirming the first eigenvector")
print(B)
print ("eigenvector multiplied by the first eigenvalue.")
C = vectors[:, 0] * values[0]
print(C)
print("The two vectors match as expected")
# confirm second eigenvector
B = A.dot(vectors[:, 1])
print("confirming the second eigenvector")
print(B)
print ("eigenvector multiplied by the second eigenvalue.")
C = vectors[:, 1] * values[1]
print(C)
print("The two vectors match as expected")

confirming the first eigenvector
[ -3.73863537  -8.46653421 -13.19443305]
eigenvector multiplied by the first eigenvalue.
[ -3.73863537  -8.46653421 -13.19443305]
The two vectors match as expected
confirming the second eigenvector
[ 0.87764976  0.09688771 -0.68387434]
eigenvector multiplied by the second eigenvalue.
[ 0.87764976  0.09688771 -0.68387434]
The two vectors match as expected


## Reconstruct the original Matrix
We can reverse the process and reconstruct the original matrix given only the eigenvectors and eigenvalues.

First, the list of eigenvectors must be converted into a matrix, where each vector becomes a row. The eigenvalues need to be arranged into a diagonal matrix. The NumPy diag() function can be used for this.

Next, we need to calculate the inverse of the eigenvector matrix, which we can achieve with the inv() NumPy function. Finally, these elements need to be multiplied together with the dot() function.

In [5]:
# reconstruct matrix
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# calculate eigenvectors and eigenvalues
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Wrap up
We discussed:
- Introduction to Eigenvalue and Eigenvectors
- Calculation of Eigendecomposition
- Confirm an Eigenvector and Eigenvalue
- Reconstruct the original matrix

Examples, thanks to Jason Brownlee PhD retrieved from: https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/