# Excercise - 1: Create a matrix and multiply the matrix by its identity?

In [4]:
import numpy as np
# Create a (3,3) array
X = np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
I2 = np.identity(3)
print(X)
print(X.dot(I2))
print(I2.dot(X))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Excercise - 2:  - Center observations to have zero mean

1. Create an array of 10 random observations with three columns - let's call this array X [10 x 3] use `np.random.random(n, n)`
2. Take the mean of each column X into an array [1 x 3]  _hint: use <array>.mean(axis=0)_
3. Subract the mean to get a representation of the original array X that is 'centered' around zero
    
For extra credit, implement the Mean Normalization formula where X  is the original value and x' is the normalized value.

$$x' = \frac{x - average(x)}{max(x) - min(x)}$$

In [102]:
# fill in the code here. Rpleace None with the proper code

X = None
# take the mean of the columns of X
X_mean = None
print("The mean of each column" , X_mean)
# subtract the mean to get the centered values
X_centered = None
# check your result by seeing if the mean of the new matrix is zero (to the precision of the cpu)
if X_centered is not None:
    print("Check your work")
    print(X_centered.mean(axis=0))



The mean of each column None


In [103]:
# Answer: 
X = np.random.random((10, 3))
print(X)
print()
# take the mean of the columns of X
X_mean = X.mean(0)
print("The mean of each column" , X_mean)
# subtract the mean to get the centered values
X_centered = X - X_mean
print(X_centered)
print("Check your work:")
print(X_centered.mean(0))

[[0.10955671 0.23034082 0.12911881]
 [0.95548795 0.01460991 0.61146307]
 [0.64003555 0.70942536 0.70114952]
 [0.44551036 0.10059025 0.743953  ]
 [0.90540154 0.48825    0.64997915]
 [0.60747308 0.99377717 0.36802317]
 [0.80167975 0.62843945 0.55705164]
 [0.44060395 0.44999859 0.82859436]
 [0.42398147 0.80858677 0.80381626]
 [0.71381209 0.97684153 0.24298307]]

The mean of each column [0.60435424 0.54008599 0.5636132 ]
[[-0.49479754 -0.30974517 -0.4344944 ]
 [ 0.3511337  -0.52547608  0.04784987]
 [ 0.03568131  0.16933937  0.13753631]
 [-0.15884388 -0.43949573  0.1803398 ]
 [ 0.30104729 -0.05183598  0.08636594]
 [ 0.00311884  0.45369119 -0.19559003]
 [ 0.19732551  0.08835347 -0.00656156]
 [-0.1637503  -0.09008739  0.26498115]
 [-0.18037277  0.26850078  0.24020305]
 [ 0.10945784  0.43675554 -0.32063014]]
Check your work:
[-5.55111512e-17 -1.11022302e-17  1.11022302e-17]
