# Outline
- Creating a 2D NumPy Array
- Seeing the “shape” of NumPy Array
- Subsetting a 2D NumPy Array

   ## Creating a 2D NumPy Array

In [24]:
import numpy as np

In [25]:
# List of masses
mass = [12,20,32]

In [26]:
# List of volumes
volume = [36, 18, 10]

In [41]:
#Create a 2D NumPy array from a list of lists
massvolume = [[12,20,32], [36, 18, 10]]

In [42]:
type(massvolume)

list

In [43]:
massvolume_array = np.array(massvolume)

In [44]:
type(massvolume_array)

numpy.ndarray

In [46]:
print(massvolume_array)

[[12 20 32]
 [36 18 10]]


## Seeing the shape of a NumPy array

In [47]:
# See how many rows and columns there are 
massvolume_array.shape

(2, 3)

## Subsetting a 2D NumPy array

In [49]:
massvolume_array[1,2]

10

In [50]:
massvolume_array[0]

array([12, 20, 32])

In [53]:
massvolume_array[0:2, 1:3]

array([[20, 32],
       [18, 10]])